-- 015_tournament_bracket.sql
-- Bracket match slots for single-elimination tournaments.
-- Generated by the organizer when they start the tournament; one row per
-- match slot across all rounds.  Round 1 is populated immediately;
-- subsequent rounds are filled as winners advance.

create table if not exists public.tournament_bracket_matches (
  id             uuid        primary key default gen_random_uuid(),
  tournament_id  uuid        not null references public.tournaments(id) on delete cascade,
  round_number   integer     not null check (round_number >= 1),
  match_number   integer     not null check (match_number >= 1),
  player1_id     uuid        references public.profiles(id),
  player2_id     uuid        references public.profiles(id),
  winner_id      uuid        references public.profiles(id),
  is_bye         boolean     not null default false,
  created_at     timestamptz not null default now(),

  unique (tournament_id, round_number, match_number)
);

-- ── Indexes ─────────────────────────────────────────────────────────────────

create index if not exists idx_bracket_tournament
  on public.tournament_bracket_matches(tournament_id);

create index if not exists idx_bracket_round
  on public.tournament_bracket_matches(tournament_id, round_number);

-- ── RLS ──────────────────────────────────────────────────────────────────────

alter table public.tournament_bracket_matches enable row level security;

-- Any authenticated user may read brackets.
create policy "bracket_select"
  on public.tournament_bracket_matches for select
  to authenticated using (true);

-- Only the tournament organiser may create bracket rows.
create policy "bracket_insert"
  on public.tournament_bracket_matches for insert
  to authenticated
  with check (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id
        and t.organizer_id = auth.uid()
    )
  );

-- Only the tournament organiser may update (record winners / advance players).
create policy "bracket_update"
  on public.tournament_bracket_matches for update
  to authenticated
  using (
    exists (
      select 1 from public.tournaments t
      where t.id = tournament_id
        and t.organizer_id = auth.uid()
    )
  );
